### ISSUE TITLE
Try implementing this lib with delta-rs

### ISSUE THREAD

**Issue by MrPowers** [rajagurunath/dask_deltatable#2]
I played around with [delta-rs](https://github.com/delta-io/delta-rs) and think that'd be an even easier way to implement the Delta read functionality.

Here's how we can get all the files that need to be read into the Dask DataFrame.

```python
from deltalake import DeltaTable

dt = DeltaTable("tmp/some-delta-pyspark")
dt.files() # list of files
```

This [to_pyarrow_dataset](https://github.com/delta-io/delta-rs/blob/e107122e1622f83db458c836d1143b27a1e4535b/python/deltalake/table.py#L234) function may be useful. There is also a to_pyarrow_table function.

What do you think @rajagurunath?

**Comment by rajagurunath** [comment]
Hi @MrPowers,

That's a great Suggestion. 👍 

We initially discussed  integrating delta-rs and dask [here](https://github.com/dask/dask/issues/8046), and at that
time, we are facing some problems to read data from s3, AzureFS, GCFS.

Now I think there was explicit support for the pyarrow filesystem to read from a different backend.

After your Suggestion, Now I have started working on delta-rs integration, and currently trying to figure out how to parallelize IO using Dask (reading multiple parquet files). if we rely on delta-rs `to_pyarraow_dataset` function all the parquet files are read in the same thread (Dask task) I guess. so planning to take all the advantages of delta-rs and implementing only the parallel reading function using Dask Delayed separately.

Any other Suggestions for parallelizing the deltalake read using Dask ?

And Once again thanks for trying this out and opening an issue here.

**Comment by MrPowers** [comment]
@rajagurunath - I actually think this is going to be super easy.

Think this will work:

```python
from deltalake import DeltaTable
import dask.dataframe as dd

dt = DeltaTable("tmp/some-delta-pyspark")
ddf = dd.read_parquet(dt.files())
```

The [read_parquet](https://docs.dask.org/en/latest/generated/dask.dataframe.read_parquet.html) method takes a list of file names.

Can you try and let me know if it works?

**Comment by MrPowers** [comment]
Sounds good, keep me posted ;)

**Comment by rajagurunath** [comment]
Hi @MrPowers,

Integrating delta-rs and dask work was almost completed, 

if you have some time can you please review the PR created here https://github.com/rajagurunath/dask_deltatable/pull/3. and let me know your suggestions for the same.

Thanks in Advance.
